# Generated by Django 5.1.4 on 2025-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_purpose', models.CharField(choices=[('TUITION FEE', 'Tuition Fee'), ('CERTIFICATE OF GRADES', 'Certificate of Grades'), ('CERTIFICATE OF GOOD MORALE', 'Certificate of Good Morale'), ('CERTIFICATE OF ENROLLMENT', 'Certificate of Enrollment'), ('OTHER', 'Other')], max_length=255, null=True)),
                ('payment_purpose_other', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('registrar_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('AVAILABLE', 'Available')], default='PENDING', max_length=255)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='media/payments/')),
            ],
        ),
    ]
