# Generated by Django 5.1.4 on 2025-02-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_purpose', models.CharField()),
                ('payment_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('registrar_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('AVAILABLE', 'Available')], default='PENDING', max_length=255)),
                ('payment_proof', models.ImageField(upload_to='payments/')),
                ('payment_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.paymentpurpose')),
            ],
        ),
    ]
