# Generated by Django 5.1.4 on 2025-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(upload_to='media/payments/'),
        ),
    ]
