# Generated by Django 5.1.4 on 2025-02-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='media/payments/'),
        ),
    ]
