# Generated by Django 5.1.4 on 2025-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='registrar_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('AVAILABLE', 'Available'), ('COMPLETE', 'Complete')], default='PENDING', max_length=255),
        ),
    ]
