# Generated by Django 5.1.4 on 2025-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_registrar_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
