# Generated by Django 5.1.4 on 2025-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_purpose',
            field=models.CharField(choices=[('CERTIFICATE OF GRADES', 'Certificate of Grades'), ('CERTIFICATE OF GOOD MORALE', 'Certificate of Good Morale'), ('CERTIFICATE OF ENROLLMENT', 'Certificate of Enrollment'), ('TRANSCRIPT OF RECORDS', 'Transcript of Records'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
