# Generated by Django 5.1.4 on 2024-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='studentUSN',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
