# Generated by Django 5.1.4 on 2025-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_usn', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('grade_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
