# Generated by Django 5.1.4 on 2025-03-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('student_usn', 'subject_code', 'subject_name', 'semester', 'year')},
        ),
    ]
