# Generated by Django 5.1.4 on 2025-01-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
